In [1]:
import os, sys
import pandas as pd

cwd = os.getcwd()

file = 'FR0000051807_20231005_TIF.parquet.gzip'

In [2]:
df = pd.read_parquet(file)
display(df)

                     side order_type         time_in_force  size
index
2023-10-05 08:20:00   Buy      Limit     Valid for Closing   0.0
2023-10-05 08:20:00   Buy      Limit  Valid for Uncrossing   0.0
2023-10-05 08:20:00   Buy     Market     Valid for Closing   0.0
2023-10-05 08:20:00   Buy     Market  Valid for Uncrossing   9.0
2023-10-05 08:20:00  Sell      Limit     Valid for Closing   0.0
...                   ...        ...                   ...   ...
2023-10-05 17:35:00   Buy     Market  Valid for Uncrossing   0.0
2023-10-05 17:35:00  Sell      Limit     Valid for Closing   0.0
2023-10-05 17:35:00  Sell      Limit  Valid for Uncrossing   0.0
2023-10-05 17:35:00  Sell     Market     Valid for Closing   0.0
2023-10-05 17:35:00  Sell     Market  Valid for Uncrossing   0.0

[880 rows x 4 columns]

In [3]:
display(df[:16])

                     side order_type         time_in_force  size
index
2023-10-05 08:20:00   Buy      Limit     Valid for Closing   0.0
2023-10-05 08:20:00   Buy      Limit  Valid for Uncrossing   0.0
2023-10-05 08:20:00   Buy     Market     Valid for Closing   0.0
2023-10-05 08:20:00   Buy     Market  Valid for Uncrossing   9.0
2023-10-05 08:20:00  Sell      Limit     Valid for Closing   0.0
2023-10-05 08:20:00  Sell      Limit  Valid for Uncrossing   0.0
2023-10-05 08:20:00  Sell     Market     Valid for Closing   0.0
2023-10-05 08:20:00  Sell     Market  Valid for Uncrossing   0.0
2023-10-05 08:25:00   Buy      Limit     Valid for Closing   0.0
2023-10-05 08:25:00   Buy      Limit  Valid for Uncrossing   0.0
2023-10-05 08:25:00   Buy     Market     Valid for Closing   0.0
2023-10-05 08:25:00   Buy     Market  Valid for Uncrossing   9.0
2023-10-05 08:25:00  Sell      Limit     Valid for Closing   0.0
2023-10-05 08:25:00  Sell      Limit  Valid for Uncrossing   0.0
2023-10-05 08:25:00  Sell     Market     Valid for Closing   0.0
2023-10-05 08:25:00  Sell     Market  Valid for Uncrossing   0.0

In [4]:
l1 = [2,3,6]
l2 = [2,3,5,7, 6]

if all(elem in l2 for elem in l1):
    print('ok')
else: print('nope')

ok

In [8]:
p = cwd
print(p)
while all(f not in os.listdir(p) for f in ['data','src']):
    p = os.path.dirname(p)
    print(p)
    
print(p)

C:\Users\Utilisateur\Desktop\doctorat\2. Recherche\Article 1\3. Python\PhD_article_1\notebooks
C:\Users\Utilisateur\Desktop\doctorat\2. Recherche\Article 1\3. Python\PhD_article_1
C:\Users\Utilisateur\Desktop\doctorat\2. Recherche\Article 1\3. Python\PhD_article_1

In [10]:
text = 'dgd_hdh_zer_dsf'
display(text.split('_')[0])

'dgd'