In [1]:
import os, sys
import pandas as pd

cwd = os.getcwd()
root_path = cwd
while '.venv' not in os.listdir(root_path):
    root_path =  os.path.dirname(root_path)
data_path = os.path.join(root_path,'data')
display(os.listdir(data_path))

['assets.csv', 'assets_DB.csv', 'assets_DB_old.csv', 'processed', 'raw']

In [6]:
df = pd.read_csv(os.path.join(data_path,'assets_DB.csv'), index_col=0)
display(df)

             ISIN     RIC       data     model optimization process
0    FR0000073272  SAF.PA      OHLCV       CNN         True    True
1    FR0000073272  SAF.PA      OHLCV      LSTM         True    True
2    FR0000073272  SAF.PA      OHLCV  CNN_LSTM         True    True
3    FR0000073272  SAF.PA        FOB       CNN            0   False
4    FR0000073272  SAF.PA        FOB      LSTM            0   False
..            ...     ...        ...       ...          ...     ...
346  NL0000235190  AIR.PA        FOB      LSTM            0   False
347  NL0000235190  AIR.PA        FOB  CNN_LSTM            0   False
348  NL0000235190  AIR.PA  OHLCV_FOB       CNN            0   False
349  NL0000235190  AIR.PA  OHLCV_FOB      LSTM            0   False
350  NL0000235190  AIR.PA  OHLCV_FOB  CNN_LSTM            0   False

[351 rows x 6 columns]

In [7]:
df = df.drop(['optimization','process'], axis=1)
df['file'] = df[['ISIN','data','model']].apply(lambda x: '_'.join(x), axis=1)
df['GSA'] = 'PENDING'
display(df)

,ISIN,RIC,data,model,file,GSA
0,FR0000073272,SAF.PA,OHLCV,CNN,FR0000073272_OHLCV_CNN,PENDING
1,FR0000073272,SAF.PA,OHLCV,LSTM,FR0000073272_OHLCV_LSTM,PENDING
2,FR0000073272,SAF.PA,OHLCV,CNN_LSTM,FR0000073272_OHLCV_CNN_LSTM,PENDING
3,FR0000073272,SAF.PA,FOB,CNN,FR0000073272_FOB_CNN,PENDING
4,FR0000073272,SAF.PA,FOB,LSTM,FR0000073272_FOB_LSTM,PENDING
...,...,...,...,...,...,...
346,NL0000235190,AIR.PA,FOB,LSTM,NL0000235190_FOB_LSTM,PENDING
347,NL0000235190,AIR.PA,FOB,CNN_LSTM,NL0000235190_FOB_CNN_LSTM,PENDING
348,NL0000235190,AIR.PA,OHLCV_FOB,CNN,NL0000235190_OHLCV_FOB_CNN,PENDING
349,NL0000235190,AIR.PA,OHLCV_FOB,LSTM,NL0000235190_OHLCV_FOB_LSTM,PENDING
350,NL0000235190,AIR.PA,OHLCV_FOB,CNN_LSTM,NL0000235190_OHLCV_FOB_CNN_LSTM,PENDING

In [8]:
df.to_csv('assets_GSA.csv')

In [12]:
display(pd.read_csv('assets_GSA.csv', index_col=0))

,ISIN,RIC,data,model,file,GSA
0,FR0000073272,SAF.PA,OHLCV,CNN,FR0000073272_OHLCV_CNN,PENDING
1,FR0000073272,SAF.PA,OHLCV,LSTM,FR0000073272_OHLCV_LSTM,PENDING
2,FR0000073272,SAF.PA,OHLCV,CNN_LSTM,FR0000073272_OHLCV_CNN_LSTM,PENDING
3,FR0000073272,SAF.PA,FOB,CNN,FR0000073272_FOB_CNN,PENDING
4,FR0000073272,SAF.PA,FOB,LSTM,FR0000073272_FOB_LSTM,PENDING
...,...,...,...,...,...,...
346,NL0000235190,AIR.PA,FOB,LSTM,NL0000235190_FOB_LSTM,PENDING
347,NL0000235190,AIR.PA,FOB,CNN_LSTM,NL0000235190_FOB_CNN_LSTM,PENDING
348,NL0000235190,AIR.PA,OHLCV_FOB,CNN,NL0000235190_OHLCV_FOB_CNN,PENDING
349,NL0000235190,AIR.PA,OHLCV_FOB,LSTM,NL0000235190_OHLCV_FOB_LSTM,PENDING
350,NL0000235190,AIR.PA,OHLCV_FOB,CNN_LSTM,NL0000235190_OHLCV_FOB_CNN_LSTM,PENDING